# Generated by Django 4.2.5 on 2023-11-17 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("native_language", models.CharField(blank=True, max_length=50)),
                ("target_language", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("full_name", models.CharField(max_length=50)),
                ("is_teacher", models.BooleanField(default=False)),
                ("zoom_access_token", models.CharField(max_length=800)),
                ("zoom_refresh_token", models.CharField(max_length=800)),
                ("zoom_token_expiration", models.CharField(max_length=512)),
                ("zoom_user_id", models.CharField(max_length=50)),
                ("is_zoom_authenticated", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="MeetingRecordings",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("meeting", models.CharField(max_length=128)),
                ("file_id", models.CharField(max_length=50)),
                ("file_name", models.CharField(max_length=128)),
                ("file_type", models.CharField(max_length=128)),
                ("file_size", models.IntegerField()),
                ("download_url", models.CharField(max_length=512)),
                ("download_token", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "meeting_recordings",
                "unique_together": {("meeting", "file_id")},
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("zoom_meeting_uuid", models.CharField(max_length=50)),
                ("host", models.CharField(max_length=128)),
                ("languages", models.JSONField(blank=True, default=list)),
                (
                    "transcription_blob",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "meeting_recordings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="meeting_recordings",
                        to="db_orm_model.meetingrecordings",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True, related_name="participants", to="db_orm_model.user"
                    ),
                ),
            ],
            options={
                "db_table": "meetings",
            },
        ),
    ]
