# Generated by Django 4.2.5 on 2023-10-04 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("zoom_meeting_uuid", models.CharField(max_length=50)),
                ("transcription_id", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("native_language", models.CharField(max_length=50)),
                ("target_language", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=50)),
                ("is_teacher", models.BooleanField(default=False)),
                ("zoom_access_token", models.CharField(max_length=512)),
                ("zoom_refresh_token", models.CharField(max_length=512)),
                ("zoom_token_expiration", models.CharField(max_length=512)),
                ("zoom_user_id", models.CharField(max_length=50)),
                ("is_zoom_authenticated", models.BooleanField(default=False)),
            ],
        ),
    ]
