# Generated by Django 4.2.5 on 2023-10-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zoom_access_token',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='zoom_refresh_token',
            field=models.CharField(max_length=1024),
        ),
    ]
