# Generated by Django 4.2.5 on 2023-12-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_orm_model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="feedback_blob",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
