# Generated by Django 4.2.5 on 2023-10-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm_model', '0002_alter_user_zoom_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zoom_access_token',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='user',
            name='zoom_refresh_token',
            field=models.CharField(max_length=800),
        ),
    ]
