# Generated by Django 4.2.5 on 2023-12-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm_model', '0002_meeting_feedback_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashed_password',
            field=models.CharField(default='Duetsai123!', max_length=50),
            preserve_default=False,
        ),
    ]
