# Generated by Django 4.2.5 on 2023-10-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm_model', '0003_alter_user_zoom_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_language',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
