# Generated by Django 4.2.5 on 2023-12-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm_model', '0003_user_hashed_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashed_password',
            field=models.CharField(max_length=128),
        ),
    ]
