# Generated by Django 4.2.5 on 2023-10-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_orm_model", "0004_alter_user_native_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting", models.CharField(max_length=128)),
                ("user", models.CharField(max_length=128)),
            ],
            options={
                "unique_together": {("meeting", "user")},
            },
        ),
    ]
