# Generated by Django 4.2.5 on 2023-12-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_orm_model", "0004_alter_user_hashed_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="zoom_meeting_uuid",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
