# Generated by Django 4.2.5 on 2024-04-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm_model', '0005_alter_meeting_zoom_meeting_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='html_file_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='session_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
