# Generated by Django 4.2.5 on 2023-10-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_orm_model", "0005_meetingparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="host",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="meeting",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="transcription_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
