# Generated by Django 4.2.5 on 2023-10-10 06:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db_orm_model", "0006_meeting_host_alter_meeting_end_time_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MeetingParticipant",
            new_name="MeetingParticipants",
        ),
    ]
