# Generated by Django 4.2.5 on 2023-10-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_orm_model", "0007_rename_meetingparticipant_meetingparticipants"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingRecordings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting", models.CharField(max_length=128)),
                ("file_id", models.CharField(max_length=50)),
                ("file_name", models.CharField(max_length=128)),
                ("file_type", models.CharField(max_length=128)),
                ("file_size", models.IntegerField()),
                ("download_url", models.CharField(max_length=512)),
                ("download_token", models.CharField(max_length=512)),
            ],
            options={
                "unique_together": {("meeting", "file_id")},
            },
        ),
    ]
