# Generated by Django 4.2.5 on 2023-10-14 00:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm_model', '0008_meetingrecordings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('meeting_uuid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_uuid', models.CharField(max_length=50)),
                ('speaker_uuid', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
            options={
                'unique_together': {('transcription_uuid', 'speaker_uuid', 'start', 'end')},
            },
        ),
    ]
