# Generated by Django 4.2.5 on 2023-10-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm_model', '0009_transcription_transcriptionelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionelement',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
