# Generated by Django 4.2.5 on 2023-10-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_orm_model", "0010_alter_transcriptionelement_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
