# Generated by Django 4.2.5 on 2023-11-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm_model', '0011_meeting_languages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transcription',
        ),
        migrations.DeleteModel(
            name='TranscriptionElement',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='transcription_id',
        ),
        migrations.AddField(
            model_name='meeting',
            name='transcription_blob',
            field=models.CharField(default='REPLACE WITH AZURE BLOB', max_length=256),
            preserve_default=False,
        ),
    ]
