# Generated by Django 4.2.5 on 2023-11-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm_model', '0012_delete_transcription_delete_transcriptionelement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='transcription_blob',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
